<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\AssemblyInfo.props" />

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoftWell.Fix.Initiator.Autofac</AssemblyName>
    <RootNamespace>SoftWell.Fix.Initiator.Autofac</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup Condition="('$(TargetFramework)'=='net7.0')">
    <PackageReference Include="Autofac" Version="6.5.0"/>
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)'=='net8.0')">
    <PackageReference Include="Autofac" Version="8.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Fix.Initiator/Fix.Initiator.csproj" />
  </ItemGroup>

</Project>